accounts/urls.py
from django.urls import path
from accounts.views import *

app_name = 'accounts'
urlpatterns = [
    path('login/', Login.as_view(), name='login'),
    path('login/google/', GoogleLoginView.as_view(), name='google_login'),
    path('login/google/callback/', GoogleCallBackView.as_view(), name='google_callback'),
    path('register/', Register.as_view(), name='register'),
    path('logout/', Logout.as_view(), name='logout'),
    path('verify_email/', VerifyRegistration.as_view(), name='verify_email'),
    path('forgot_password/', ForgotPassword.as_view(), name="forgot_password"),
    path('check_email/', CheckEmail.as_view(), name='check_email'),
    path('create_new_password/', CreateNewPassword.as_view(), name="create_new_password"),
    path('profile/', Profile.as_view(), name='profile'),
    path('profile/edit/', ProfileEdit.as_view(), name='profile_edit'),
    path('verify_email_to_change_email/', VerifyEmailToChangeEmail.as_view(), name='VerifyEmailToChangeEmail')

]

carts/urls.py
from django.urls import path, include
from carts.views import *

app_name = 'cart'
urlpatterns = [
    path('', CartView.as_view(), name='list'),
    path('add_item/<int:pk>', AddCartItem.as_view(), name='add_cart_item'),
    path('update_item/<int:pk>', UpdateCartItem.as_view(), name='update_cart_item'),
    path('remove_item/<int:pk>', RemoveCartItem.as_view(), name='remove_cart_item'),
    path('remove_cart_item_in_list/<int:pk>', remove_cart_item_in_list, name='remove_cart_item_in_list'),
    path('clear/', ClearCartItem.as_view(), name='clear_cart')

]

config/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.i18n import set_language

from eshop.views import home
from favourites.views import FavouriteView, AddFavouriteItem, RemoveFavouriteItem, ClearFavourites

urlpatterns = [
    path('rosetta/', include('rosetta.urls')),
    path('i18n/', include('django.conf.urls.i18n')),

]

urlpatterns += i18n_patterns(
    path('', home, name='home'),
    path('admin/', admin.site.urls),
    path('shops/', include('shops.urls')),
    path('products/', include('products.urls')),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('carts.urls')),
    path('payment/', include('payments.urls')),
    path('orders/', include('orders.urls')),
    path('feedbacks/', include('reviews.urls')),
    path('common/', include('common.urls')),
    path('favourites/', include('favourites.urls')),
    path('notifications/', include('notifications.urls'))
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/forms.py
from django import forms
from django.core.exceptions import ValidationError
from accounts.models import User, Address
from accounts.utils import get_random_username
from django.utils.translation import gettext_lazy as _


class UserLoginForm(forms.Form):
    email = forms.EmailField(label=_("Email"))
    password = forms.CharField(label=_("Password"), max_length=255, widget=forms.PasswordInput())

    class Meta:
        labels = {
            'email': _("Email")
        }


class UserRegisterForm(forms.ModelForm):
    re_password = forms.CharField(
        label=_("Repeat Password"),
        max_length=255,
        widget=forms.PasswordInput()
    )

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'password', 're_password']
        widgets = {
            'password': forms.PasswordInput()
        }
        labels = {
            'first_name': _("First Name"),
            'last_name': _("Last Name"),
            'email': _("Email"),
            'password': _("Password"),
        }

    def validate_passwords(self, *args, **kwargs):
        re_password = self.cleaned_data.get('re_password')
        password = self.cleaned_data.get('password')
        if str(password) != str(re_password):
            self.add_error('password', _("Passwords don't match."))
            return ValidationError(_("Passwords don't match."))
        return password

    def save(self, commit=True):
        self.cleaned_data.pop('re_password')
        user = User.objects.create_user(get_random_username(), **self.cleaned_data)
        user.is_verified_email = False
        return user


class UserForgotPasswordForm(forms.Form):
    email = forms.EmailField(label=_("Email"))


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']
        labels = {
            'first_name': _("First Name"),
            'last_name': _("Last Name"),
            'email': _("Email"),
        }


class UserAddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = '__all__'
        exclude = ['user']
        labels = {
            'address_line_1': _("Address Line 1"),
            'address_line_2': _("Address Line 2"),
            'city': _("City"),
            'state_or_province': _("State or Province"),
            'country': _("Country"),
            'postal_code': _("Postal Code"),
            'is_primary': _("Primary Address"),
        }

accounts/views.py
import requests
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from accounts.forms import *
from accounts.service import *
from django.http import JsonResponse, HttpResponse
from accounts.models import CodeEmail, User, CodePassword
from django.utils import timezone
from django.contrib import messages
from django.core.cache import cache
from django.views.decorators.cache import cache_page
from django_ratelimit.decorators import ratelimit
from django.contrib.auth.mixins import LoginRequiredMixin
from django.conf import settings
from django.utils.decorators import method_decorator
from django.db import transaction


class Login(View):
    @method_decorator(ratelimit(key='user_or_ip', rate='6/m', block=True))
    def get(self, request):
        form = UserLoginForm()
        return render(request, 'accounts/login.html', {'form': form})

    @method_decorator(ratelimit(key='user_or_ip', rate='6/m', block=True))
    def post(self, request):
        form = UserLoginForm(request.POST)
        if form.is_valid():
            user = authenticate(request, **form.cleaned_data)
            if not user:
                form.add_error('email', 'Username or password is incorrect')
                return render(request, 'accounts/login.html', {'form': form})

            login(request, user)
            return redirect('products:products')

        return redirect('accounts:login')


class Register(View):
    @method_decorator(ratelimit(key='user_or_ip', rate='100/m', block=True))
    def get(self, request):
        form = UserRegisterForm()
        return render(request, 'accounts/register.html', {'form': form})

    @method_decorator(ratelimit(key='user_or_ip', rate='20/m', block=True))
    @method_decorator(transaction.atomic)
    def post(self, request):
        form = UserRegisterForm(request.POST)
        if form.is_valid() and form.validate_passwords():
            email = request.POST.get('email')
            first_name = request.POST.get('first_name')
            send_email_verification(email, first_name)
            form.save()
            return JsonResponse({'success': True})

        #TODO
        print(form.errors)
        return JsonResponse({'success': False, 'errors': form.errors})


class Logout(View):
    def get(self, request):
        logout(request)
        return redirect('products:products')


class VerifyRegistration(View):
    @method_decorator(ratelimit(key='user_or_ip', rate='6/m', block=True))
    @method_decorator(transaction.atomic)
    def post(self, request):
        verification_code = request.POST.get('verification_code')
        email = request.POST.get('email')

        if not email or not verification_code:
            return JsonResponse({
                'success': False,
                'error': 'Missing required fields'
            }, status=400)

        code_db =  CodeEmail.objects.filter(email=email).first()

        if not code_db:
            return JsonResponse({'success': False, 'error': 'Unexpected error occurred'})

        if code_db.expire_date < timezone.now():
            return JsonResponse({'success': False, 'error': 'Code is already expired, please try again later.'})

        if str(code_db.code) != str(verification_code):
            return JsonResponse({'success': False, 'error': 'Code is incorrect, please try again.'})

        user = User.objects.filter(email=email).first()
        user.is_verified_email = True
        user.save()
        CodeEmail.objects.filter(email=email).first().delete()
        return JsonResponse({'success': True, 'redirect_url': '/accounts/login/'})


class ForgotPassword(View):
    @method_decorator(ratelimit(key='user_or_ip', rate='6/m', block=True))
    def get(self, request):
        form = UserForgotPasswordForm()
        return render(request, 'accounts/reset_password.html', {'form': form})

    @method_decorator(ratelimit(key='user_or_ip', rate='6/m', block=True))
    @method_decorator(transaction.atomic)
    def post(self, request):
        form = UserForgotPasswordForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('email')
            user = User.objects.filter(email=email).first()
            if not user:
                form.add_error('email', 'User with this email doesn\'t exists.')
                return render(request, 'accounts/reset_password.html', {'form': form})

            send_password_verification(user)
            request.session['reset_email'] = email
            return redirect('accounts:check_email')

        return render(request, 'accounts/reset_password.html', {'form': form})


class CheckEmail(View):
    @method_decorator(ratelimit(key='user_or_ip', rate='6/m', block=True))
    def get(self, request):
        return render(request, 'accounts/check_email.html')

    @method_decorator(ratelimit(key='user_or_ip', rate='6/m', block=True))
    def post(self, request):
        code = request.POST.get('verification_code')
        email = request.session.get('reset_email')
        if not code or not email:
            messages.error(request, 'Email or Code number didn\'t received, please try again.')
            return render(request, 'accounts/check_email.html')

        code_db = CodePassword.objects.filter(user=User.objects.filter(email=email).first()).first()

        if not code_db:
            messages.error(request, "Invalid verification code. Please try again.")
            return render(request, 'accounts/check_email.html')

        if code_db.expire_date < timezone.now():
            messages.error(request, "Your code has expired. Request a new one.")
            return render(request, 'accounts/check_email.html')

        if str(code_db.code) != str(code):
            messages.error(request, "Incorrect code. Please enter the correct code.")
            return render(request, 'accounts/check_email.html')

        request.session['reset_email'] = email

        return redirect('accounts:create_new_password')


class CreateNewPassword(View):
    @method_decorator(ratelimit(key='user_or_ip', rate='6/m', block=True))
    def get(self, request):
        if not request.session.get('reset_email', False):
            return HttpResponse("Email is not verified")
        return render(request, 'accounts/create_new_password.html')

    @method_decorator(ratelimit(key='user_or_ip', rate='6/m', block=True))
    @method_decorator(transaction.atomic)
    def post(self, request):
        password = request.POST.get('password')
        confirm_password = request.POST.get('confirm_password')

        if not password or not confirm_password:
            messages.error(request, 'Passwords didn\'t received. Please try again.')
            return render(request, 'accounts/create_new_password.html')

        if str(password) != str(confirm_password):
            messages.error(request, "Passwords didn\'t match.")
            return render(request, 'accounts/create_new_password.html')

        email = request.session.get('reset_email')
        if not email:
            messages.error(request, "Unexpected error occurred in server. No email received. Perhaps you deleted email session?")

        user = User.objects.filter(email=email).first()
        user.set_password(password)
        user.save()
        return redirect('accounts:login')


class Profile(View):
    @method_decorator(login_required)
    def get(self, request):
        profile_form = UserProfileForm(instance=request.user)
        current_address = Address.objects.filter(user=request.user).first()
        if current_address:
            address_form = UserAddressForm(instance=current_address)
        else:
            address_form = UserAddressForm()

        data = {
            'profile_form': profile_form,
            'address_form': address_form
        }
        return render(request, 'accounts/profile.html', context=data)


class ProfileEdit(LoginRequiredMixin, View):
    def get(self, request):
        profile_form = UserProfileForm(instance=request.user)
        current_address = Address.objects.filter(user=request.user).first()
        if current_address:
            address_form = UserAddressForm(instance=current_address)
        else:
            address_form = UserAddressForm()

        data = {
            'profile_form': profile_form,
            'address_form': address_form
        }
        return render(request, 'accounts/profile_edit.html', context=data)

    @method_decorator(transaction.atomic)
    def post(self, request):
        profile_form = UserProfileForm(request.POST, instance=request.user)
        current_address = Address.objects.filter(user=request.user).first()

        if current_address:
            address_form = UserAddressForm(request.POST, instance=current_address)
        else:
            address_form = UserAddressForm(request.POST)

        if profile_form.is_valid() and address_form.is_valid():
            address = address_form.save(commit=False)
            address.user = request.user
            address.save()

            new_email = profile_form.cleaned_data.get('email')
            user_db = User.objects.filter(id=request.user.pk).first()
            if str(new_email) != str(user_db.email):
                request.session['new_email'] = new_email
                send_email_to_verify_email(new_email, profile_form.cleaned_data.get('first_name'))

                user_form = profile_form.save(commit=False)
                user_form.first_name = profile_form.cleaned_data.get('first_name')
                user_form.last_name = profile_form.cleaned_data.get('last_name')
                user_form.email = user_db.email
                user_form.save()

                return redirect('accounts:VerifyEmailToChangeEmail')
            profile_form.save()

            return redirect('accounts:profile')

        data = {

templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block title %}{% trans 'Login' %}{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}

{% block content %}
    <div class="login-container">
        <div class="login-card">
            <div class="card-side card-left">
                <div class="background-elements">
                    <div class="circle circle-1"></div>
                    <div class="circle circle-2"></div>
                    <div class="circle circle-3"></div>
                    <div class="wave"></div>
                </div>
                <div class="brand">
                    <h1>{% trans 'Welcome Back' %}</h1>
                    <p>{% trans 'Sign in to continue your shopping journey' %}</p>
                </div>
            </div>
            <div class="card-side card-right">
                <div class="form-header">
                    <h2>{% trans 'Login' %}</h2>
                    <p>{% trans 'Please enter your credentials' %}</p>
                </div>

                <!-- Google Login Button -->
                <div class="social-login-container">
                    <a href="{% url 'accounts:google_login' %}" class="google-btn">
                        <div class="google-icon-wrapper">
                            <svg class="google-icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                                <path d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z"
                                      fill="#4285F4"/>
                                <path d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z"
                                      fill="#34A853"/>
                                <path d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z"
                                      fill="#FBBC05"/>
                                <path d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z"
                                      fill="#EA4335"/>
                            </svg>
                        </div>
                        <span class="google-btn-text">{% trans 'Continue with Google' %}</span>
                    </a>
                </div>

                <div class="form-separator">
                    <span>{% trans 'or login with email' %}</span>
                </div>

                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="{{ form.email.id_for_label }}">{% trans 'Email Address' %}</label>
                        <div class="input-icon">
                            <i class="fas fa-envelope"></i>
                        </div>
                        {{ form.email }}
                    </div>
                    <div class="form-group">
                        <label for="{{ form.password.id_for_label }}">{% trans 'Password' %}</label>
                        <div class="input-icon">
                            <i class="fas fa-lock"></i>
                        </div>
                        {{ form.password }}
                    </div>
                    <div class="form-options">
                        <div class="remember-me">
                            <input type="checkbox" id="remember">
                            <label for="remember">{% trans 'Remember me' %}</label>
                        </div>
                        <a href="{% url 'accounts:forgot_password' %}"
                           class="forgot-password">{% trans 'Forgot Password?' %}</a>
                    </div>
                    <button type="submit" class="login-btn">
                        <span>{% trans 'Log In' %}</span>
                        <i class="fas fa-arrow-right"></i>
                    </button>
                    <div class="register-link">
                        {% trans 'Don\'t have an account?' %} <a href="{% url 'accounts:register' %}">{% trans 'Register' %}</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block footer %}{% endblock %}

{% block extra_js %}
    <script src="{% static 'js/login.js' %}"></script>
{% endblock %}

templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block extra_css %}
<style>
  /* Scoped CSS: all rules are nested under .profile-container */
  .profile-container {
    max-width: 800px;
    margin: 40px auto;
    padding: 30px;
    border-radius: 12px;
    box-shadow: 0 4px 16px rgba(0, 0, 0, 0.1);
    background-color: #fff;
  }

  .profile-container .profile-header {
    display: flex;
    align-items: center;
    margin-bottom: 30px;
    border-bottom: 1px solid #eee;
    padding-bottom: 20px;
  }

  .profile-container .profile-avatar {
    width: 100px;
    height: 100px;
    border-radius: 50%;
    background-color: #e9ecef;
    display: flex;
    align-items: center;
    justify-content: center;
    margin-right: 20px;
    font-size: 36px;
    color: #6c757d;
  }

  .profile-container .profile-title {
    margin: 0;
    color: #343a40;
  }

  .profile-container .profile-section {
    margin-bottom: 30px;
  }

  .profile-container .section-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 15px;
    padding-bottom: 10px;
    border-bottom: 1px solid #eee;
  }

  .profile-container .edit-button {
    background-color: #f8f9fa;
    border: 1px solid #dee2e6;
    color: #495057;
    padding: 5px 15px;
    border-radius: 6px;
    text-decoration: none;
    font-size: 14px;
    transition: all 0.2s;
  }

  .profile-container .edit-button:hover {
    background-color: #e9ecef;
    color: #212529;
  }

  .profile-container .info-group {
    display: grid;
    grid-template-columns: 1fr 2fr;
    row-gap: 15px;
    column-gap: 20px;
    margin-bottom: 5px;
  }

  .profile-container .info-label {
    font-weight: 600;
    color: #6c757d;
  }

  .profile-container .info-value {
    color: #212529;
  }

  @media (max-width: 768px) {
    .profile-container {
      padding: 20px;
      margin: 20px;
    }

    .profile-container .info-group {
      grid-template-columns: 1fr;
    }
  }
</style>
{% endblock %}

{% block content %}
<div class="profile-container">
  <div class="profile-header">
    <div class="profile-avatar">
      {{ request.user.first_name|slice:":1" }}{{ request.user.last_name|slice:":1" }}
    </div>
    <div>
      <h1 class="profile-title">{{ request.user.first_name }} {{ request.user.last_name }}</h1>
      <p>{{ request.user.email }}</p>
    </div>
  </div>

  <div class="profile-section">
    <div class="section-header">
      <h2>{% trans 'Personal Information' %}</h2>
      <a href="{% url 'accounts:profile_edit' %}" class="edit-button">{% trans 'Edit' %}</a>
    </div>

    <div class="info-group">
      <div class="info-label">{% trans 'First Name' %}</div>
      <div class="info-value">{{ request.user.first_name }}</div>

      <div class="info-label">{% trans 'Last Name' %}</div>
      <div class="info-value">{{ request.user.last_name }}</div>

      <div class="info-label">{% trans 'Email' %}</div>
      <div class="info-value">{{ request.user.email }}</div>
    </div>
  </div>

  <div class="profile-section">
    <div class="section-header">
      <h2>{% trans 'Address Details' %}</h2>
      <a href="{% url 'accounts:profile_edit' %}" class="edit-button">{% trans 'Edit' %}</a>
    </div>

    {% if address_form.instance.id %}
    <div class="info-group">
      <div class="info-label">{% trans 'Address Line 1' %}</div>
      <div class="info-value">{{ address_form.instance.address_line_1 }}</div>

      {% if address_form.instance.address_line_2 %}
      <div class="info-label">{% trans 'Address Line 2' %}</div>
      <div class="info-value">{{ address_form.instance.address_line_2 }}</div>
      {% endif %}

      <div class="info-label">{% trans 'City' %}</div>
      <div class="info-value">{{ address_form.instance.city }}</div>

      <div class="info-label">{% trans 'State/Province' %}</div>
      <div class="info-value">{{ address_form.instance.state_or_province }}</div>

      <div class="info-label">{% trans 'Country' %}</div>
      <div class="info-value">{{ address_form.instance.country }}</div>

      <div class="info-label">{% trans 'Postal Code' %}</div>
      <div class="info-value">{{ address_form.instance.postal_code }}</div>

      <div class="info-label">{% trans 'Is primary address' %}</div>
      <div class="info-value">{{ address_form.instance.is_primary }}</div>
    </div>
    {% else %}
    <p>{% trans 'No address information has been added yet.' %} <a href="{% url 'accounts:profile_edit' %}">{% trans 'Add address details' %}</a></p>
    {% endif %}
  </div>
</div>
{% endblock %}

templates/accounts/profile_edit.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block content %}
<div class="edit-container">
  <div class="edit-header">
    <h1 class="edit-title">{% trans 'Edit Profile' %}</h1>
    <p>{% trans 'Update your personal information and address details' %}</p>
  </div>

  <form method="post" action="{% url 'accounts:profile_edit' %}">
    {% csrf_token %}

    <div class="form-section">
      <h2 class="section-title">{% trans 'Personal Information' %}</h2>

      <div class="form-group">
        <label for="{{ profile_form.first_name.id_for_label }}">{% trans 'First Name' %}</label>
        {{ profile_form.first_name }}
        {% if profile_form.first_name.errors %}
          <ul class="errorlist">
            {% for error in profile_form.first_name.errors %}
              <li>{{ error }}</li>
            {% endfor %}
          </ul>
        {% endif %}
      </div>

      <div class="form-group">
        <label for="{{ profile_form.last_name.id_for_label }}">{% trans 'Last Name' %}</label>
        {{ profile_form.last_name }}
        {% if profile_form.last_name.errors %}
          <ul class="errorlist">
            {% for error in profile_form.last_name.errors %}
              <li>{{ error }}</li>
            {% endfor %}
          </ul>
        {% endif %}
      </div>

      <div class="form-group">
        <label for="{{ profile_form.email.id_for_label }}">{% trans 'Email' %}</label>
        {{ profile_form.email }}
        {% if profile_form.email.errors %}
          <ul class="errorlist">
            {% for error in profile_form.email.errors %}
              <li>{{ error }}</li>
            {% endfor %}
          </ul>
        {% endif %}
      </div>
    </div>

    <div class="form-section">
      <h2 class="section-title">{% trans 'Address Details' %}</h2>

      <div class="form-group">
        <label for="{{ address_form.address_line_1.id_for_label }}">{% trans 'Address Line 1' %}</label>
        {{ address_form.address_line_1 }}
        {% if address_form.address_line_1.errors %}
          <ul class="errorlist">
            {% for error in address_form.address_line_1.errors %}
              <li>{{ error }}</li>
            {% endfor %}
          </ul>
        {% endif %}
      </div>

      <div class="form-group">
        <label for="{{ address_form.address_line_2.id_for_label }}">{% trans 'Address Line 2 (Optional)' %}</label>
        {{ address_form.address_line_2 }}
        {% if address_form.address_line_2.errors %}
          <ul class="errorlist">
            {% for error in address_form.address_line_2.errors %}
              <li>{{ error }}</li>
            {% endfor %}
          </ul>
        {% endif %}
      </div>

      <div class="form-group">
        <label for="{{ address_form.city.id_for_label }}">{% trans 'City' %}</label>
        {{ address_form.city }}
        {% if address_form.city.errors %}
          <ul class="errorlist">
            {% for error in address_form.city.errors %}
              <li>{{ error }}</li>
            {% endfor %}
          </ul>
        {% endif %}
      </div>

      <div class="form-group">
        <label for="{{ address_form.state_or_province.id_for_label }}">{% trans 'State/Province' %}</label>
        {{ address_form.state_or_province }}
        {% if address_form.state_or_province.errors %}
          <ul class="errorlist">
            {% for error in address_form.state_or_province.errors %}
              <li>{{ error }}</li>
            {% endfor %}
          </ul>
        {% endif %}
      </div>

      <div class="form-group">
        <label for="{{ address_form.country.id_for_label }}">{% trans 'Country' %}</label>
        {{ address_form.country }}
        {% if address_form.country.errors %}
          <ul class="errorlist">
            {% for error in address_form.country.errors %}
              <li>{{ error }}</li>
            {% endfor %}
          </ul>
        {% endif %}
      </div>

      <div class="form-group">
        <label for="{{ address_form.postal_code.id_for_label }}">{% trans 'Postal Code' %}</label>
        {{ address_form.postal_code }}
        {% if address_form.postal_code.errors %}
          <ul class="errorlist">
            {% for error in address_form.postal_code.errors %}
              <li>{{ error }}</li>
            {% endfor %}
          </ul>
        {% endif %}
      </div>

      <div class="form-group">
        <label for="{{ address_form.is_primary.id_for_label }}">{% trans 'Is primary address' %}</label>
        {{ address_form.is_primary }}
      </div>

    </div>

    <div class="button-group">
      <a href="{% url 'accounts:profile' %}" class="cancel-button">{% trans 'Cancel' %}</a>
      <button type="submit" class="save-button">{% trans 'Save Changes' %}</button>
    </div>
  </form>
</div>
{% endblock %}

{% block extra_css %}
<style>
  .edit-container {
    max-width: 800px;
    margin: 40px auto;
    padding: 30px;
    border-radius: 12px;
    box-shadow: 0 4px 16px rgba(0, 0, 0, 0.1);
    background-color: #fff;
  }

  .edit-header {
    margin-bottom: 30px;
    border-bottom: 1px solid #eee;
    padding-bottom: 20px;
  }

  .edit-title {
    margin: 0 0 10px 0;
    color: #343a40;
  }

  .form-section {
    margin-bottom: 30px;
  }

  .section-title {
    font-size: 1.4rem;
    margin-bottom: 20px;
    padding-bottom: 10px;
    border-bottom: 1px solid #eee;
  }

  .form-group {
    margin-bottom: 20px;
  }

  label {
    display: block;
    font-weight: 600;
    margin-bottom: 8px;
    color: #495057;
  }

  input[type="text"],
  input[type="email"],
  input[type="password"] {
    width: 100%;
    padding: 10px 15px;
    border: 1px solid #ced4da;
    border-radius: 6px;
    font-size: 16px;
  }

  input[type="text"]:focus,
  input[type="email"]:focus,
  input[type="password"]:focus {
    border-color: #80bdff;
    outline: 0;
    box-shadow: 0 0 0 0.2rem rgba(0, 123, 255, 0.25);
  }

  .button-group {
    display: flex;
    justify-content: flex-end;
    margin-top: 30px;
    gap: 15px;
  }

  .cancel-button {
    background-color: #f8f9fa;
    border: 1px solid #dee2e6;
    color: #495057;
    padding: 10px 20px;
    border-radius: 6px;
    text-decoration: none;
    font-size: 16px;
    cursor: pointer;
  }

  .save-button {
    background-color: #007bff;
    border: 1px solid #007bff;
    color: white;
    padding: 10px 20px;
    border-radius: 6px;
    font-size: 16px;
    cursor: pointer;
  }

  .save-button:hover {
    background-color: #0069d9;
    border-color: #0062cc;
  }

  .cancel-button:hover {
    background-color: #e9ecef;
    color: #212529;
  }

  .errorlist {
    color: #dc3545;
    list-style-type: none;
    padding: 0;
    margin: 5px 0 0 0;
    font-size: 14px;
  }

  @media (max-width: 768px) {
    .edit-container {
      padding: 20px;
      margin: 20px;
    }
  }
</style>
{% endblock %}