accounts/urls.py
from django.urls import path
from accounts.views import *

app_name = 'accounts'
urlpatterns = [
    path('login/', Login.as_view(), name='login'),
    path('login/google/', GoogleLoginView.as_view(), name='google_login'),
    path('login/google/callback/', GoogleCallBackView.as_view(), name='google_callback'),
    path('register/', Register.as_view(), name='register'),
    path('logout/', Logout.as_view(), name='logout'),
    path('verify_email/', VerifyRegistration.as_view(), name='verify_email'),
    path('forgot_password/', ForgotPassword.as_view(), name="forgot_password"),
    path('check_email/', CheckEmail.as_view(), name='check_email'),
    path('create_new_password/', CreateNewPassword.as_view(), name="create_new_password"),
    path('profile/', Profile.as_view(), name='profile'),
    path('profile/edit/', ProfileEdit.as_view(), name='profile_edit'),
    path('verify_email_to_change_email/', VerifyEmailToChangeEmail.as_view(), name='VerifyEmailToChangeEmail')

]

carts/urls.py
from django.urls import path, include
from carts.views import *

app_name = 'cart'
urlpatterns = [
    path('', CartView.as_view(), name='list'),
    path('add_item/<int:pk>', AddCartItem.as_view(), name='add_cart_item'),
    path('update_item/<int:pk>', UpdateCartItem.as_view(), name='update_cart_item'),
    path('remove_item/<int:pk>', RemoveCartItem.as_view(), name='remove_cart_item'),
    path('remove_cart_item_in_list/<int:pk>', remove_cart_item_in_list, name='remove_cart_item_in_list'),
    path('clear/', ClearCartItem.as_view(), name='clear_cart')

]

config/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.i18n import set_language

from eshop.views import home
from favourites.views import FavouriteView, AddFavouriteItem, RemoveFavouriteItem, ClearFavourites

urlpatterns = [
    path('rosetta/', include('rosetta.urls')),
    path('i18n/', include('django.conf.urls.i18n')),

]

urlpatterns += i18n_patterns(
    path('', home, name='home'),
    path('admin/', admin.site.urls),
    path('shops/', include('shops.urls')),
    path('products/', include('products.urls')),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('carts.urls')),
    path('payment/', include('payments.urls')),
    path('orders/', include('orders.urls')),
    path('feedbacks/', include('reviews.urls')),
    path('common/', include('common.urls')),
    path('favourites/', include('favourites.urls')),
    path('notifications/', include('notifications.urls'))
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eshop/urls.py
from django.urls import path
from .views import *



app_name='shop'
urlpatterns = [
    path('', home, name='home'),
    path('list/', ListProductView.as_view(), name='list_products'),
    path('add_product/', AddProductView.as_view(), name='add_product'),
    path('find_and_edit_product', FindAndEditProduct.as_view(), name='find_and_edit_product'),
    path('edit_product/<int:pk>', EditProductView.as_view(), name='edit_product'),

    path('find_and_delete_product', FindAndDeleteProduct.as_view(), name='find_and_delete_product'),
    path('delete_product/<int:pk>', delete_product, name='delete_product')
]

templates/check-email.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
    <form action="{% url 'accounts:check_email' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="code">{% trans 'Verification code' %}</label>
            <input type="text" maxlength="4" id="code" name="code" placeholder="{% trans 'Enter 4-digit code' %}..." required>
            {% for message in messages %}
                <p style="color: red; font-size: 13px;">{{ message }}</p>
            {% endfor %}
        </div>
        <button type="submit">{% trans 'Submit' %}</button>
    </form>
{% endblock %}

templates/create-new-password.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="new-password">{% trans 'New password' %}</label>
            <input type="password" required name="password" id="new-password">

            <label for="confirm-password">{% trans 'Confirm password' %}</label>
            <input type="password" required name="re-password" id="confirm-password">

            {% for message in messages %}
                <p style="color: red; font-size: 13px;">{{ message }}</p>
            {% endfor %}
        </div>

        <button type="submit">{% trans 'Change Password' %}</button>
    </form>
{% endblock %}

templates/find_and_delete_product.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}
    {% trans 'Product lists' %}
{% endblock %}

{% block content %}
    <div class="container">
        <h1 class="text-center m-3">{% trans 'Products lists' %}</h1>
        <div class="cart-container d-flex gap-5 justify-content-center ">
            {% for product in products %}
                <div class="card" style="width: 18rem; border: 2px solid gray;">
                    <div class="card-body">
                        <h5 class="card-title">{{ product.name }}</h5>
                        <p class="card-text">{% trans 'Description:' %} {{ product.description }}</p>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">{% trans 'Price:' %} {{ product.price }}$</li>
                        <li class="list-group-item">{% trans 'Created at:' %} {{ product.created_at }}</li>
                    </ul>
                    <div class="card-body">
                        <a class="btn btn-danger" href="{% url 'shop:delete_product' product.pk %}">{% trans 'Delete product' %}</a>

                    </div>
                </div>
                <br>
            {% empty %}
                <p>{% trans 'No products available' %}</p>
            {% endfor %}
        </div>
    </div>

    {% include 'page.html' with page=products %}

    <style>
        .cart-container {
            flex-wrap: wrap;
        }

        .card {
            box-shadow: 3px 3px 10px rgba(0, 0, 0, 0.1);
            border-radius: 8px;
            transition: transform 0.3s ease-in-out;
        }

        .card:hover {
            transform: scale(1.04);
        }

        .card-body {
            background-color: #eceff2;
        }
    </style>
{% endblock %}

templates/find_and_edit_product.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}
{% trans 'Product lists' %}
{% endblock %}

{% block content %}
    <div class="container">
        <h1 class="text-center m-3">{% trans 'Products lists' %}</h1>
        <div class="cart-container d-flex gap-5 justify-content-center ">
            {% for product in products %}
                <div class="card" style="width: 18rem; border: 2px solid gray;">
                    <div class="card-body">
                        <h5 class="card-title">{{ product.name }}</h5>
                        <p class="card-text">{% trans 'Description:' %} {{ product.description }}</p>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">{% trans 'Price:' %} {{ product.price }}$</li>
                        <li class="list-group-item">{% trans 'Created at:' %} {{ product.created_at }}</li>
                    </ul>
                    <div class="card-body">
                        <a class="btn btn-secondary" href="{% url 'shop:edit_product' product.pk %}">{% trans 'Edit product' %}</a>

                    </div>
                </div>
                <br>
            {% empty %}
                <p>{% trans 'No products available' %}</p>
            {% endfor %}
        </div>
    </div>

    {% include 'page.html' with page=products %}

    <style>
        .cart-container {
            flex-wrap: wrap;
        }

        .card {
            box-shadow: 3px 3px 10px rgba(0, 0, 0, 0.1);
            border-radius: 8px;
            transition: transform 0.3s ease-in-out;
        }

        .card:hover {
            transform: scale(1.04);
        }

        .card-body {
            background-color: #eceff2;
        }
    </style>
{% endblock %}

templates/forgot-password.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}

    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="email">{% trans 'Email' %}</label>
            <input type="email" name="email" id="email" placeholder="{% trans 'Enter your email address' %}...">
        </div>
        {% for message in messages %}
            <p style="color: red; font-size: 13px;">{{ message }}</p>
        {% endfor %}
        <div class="submit-class">
            <button type="submit">{% trans 'Send Verification Code' %}</button>
        </div>


    </form>
{% endblock %}

templates/page.html
{% load i18n %}
<nav aria-label="Page navigation">
    <ul class="pagination">
        {% if not page.has_previous %}
            <li class="page-item page-arrow disabled">
                <a class="page-link"><i class="fa fa-arrow-left"></i><span class="visually-hidden">{% trans 'Previous' %}</span></a>
            </li>
        {% else %}
            <li class="page-item page-arrow">
                <a class="page-link" href="?page={{ page.previous_page_number }}&q={{ q }}"><i class="fa fa-arrow-left"></i><span class="visually-hidden">{% trans 'Previous' %}</span></a>
            </li>
        {% endif %}

        {% for p in page.paginator.page_range %}
            {% if p == page.number %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="?page={{ p }}&q={{ q }}">{{ p }}</a>
                </li>
            {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ p }}&q={{ q }}">{{ p }}</a></li>
            {% endif %}
        {% endfor %}

        {% if not page.has_next %}
            <li class="page-item page-arrow disabled">
                <a class="page-link"><i class="fa fa-arrow-right"></i><span class="visually-hidden">{% trans 'Next' %}</span></a>
            </li>
        {% else %}
            <li class="page-item page-arrow">
                <a class="page-link" href="?page={{ page.next_page_number }}&q={{ q }}"><i class="fa fa-arrow-right"></i><span class="visually-hidden">{% trans 'Next' %}</span></a>
            </li>
        {% endif %}
    </ul>
</nav>